/**:
  ros__parameters:
    odom_rate: 50.0
    frame_id: "map"
    child_frame_id: "base_link"
    pose:
      is_with_cov: false
      overwrite_cov: false
      cov: [0.1, 0.0, 0.0,  0.0,  0.0,  0.0,
            0.0, 0.1, 0.0,  0.0,  0.0,  0.0,
            0.0, 0.0, 0.0,  0.0,  0.0,  0.0,
            0.0, 0.0, 0.0,  0.0,  0.0,  0.0,
            0.0, 0.0, 0.0,  0.0,  0.0,  0.0,
            0.0, 0.0, 0.0,  0.0,  0.0,  0.05]
    twist:
      is_with_cov: true
      overwrite_cov: false
      cov: [0.1, 0.0, 0.0,  0.0,  0.0,  0.0,
            0.0, 0.0, 0.0,  0.0,  0.0,  0.0,
            0.0, 0.0, 0.0,  0.0,  0.0,  0.0,
            0.0, 0.0, 0.0,  0.0,  0.0,  0.0,
            0.0, 0.0, 0.0,  0.0,  0.0,  0.0,
            0.0, 0.0, 0.0,  0.0,  0.0,  0.05]
